### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by sbera7** [jhlau/twitter-deepgeo#2]
I am unable to find the training data. Please can you provide the training data?

**Comment by jhlau** [comment]
We don't provide the training data, see readme how to get the training data.

**Comment by sbera7** [comment]
I am facing some issues getting the training data from their website. Can you provide it?

**Comment by jhlau** [comment]
I can't unfortunately (we've since deleted the data). You should contact to the workshop organisers and see what they can do.

**Comment by sbera7** [comment]
Ok, thank you!
